@extends('layouts.layouts')
@section('title')
    Содержание
@endsection
@section('head-js')
    <script defer src="{{ asset('js/content.js') }}"></script>
@endsection
@section('head-css')
    <link href="{{ asset('css/content.css') }}" rel="stylesheet">
@endsection
@section('style-body')
    class="body-min"
@endsection
@section('svg-icons')
    <svg-icons></svg-icons>
@endsection
@section('aside')
    <aside-main></aside-main>
@endsection
@section('header')
    <header-main></header-main>
@endsection
@section('content')
    <page-content></page-content>
@endsection
@section('footer')
    <footer-main></footer-main>
@endsection
@section('template')
    <modal-write-us></modal-write-us>
    <modal-vacancy></modal-vacancy>
    <modal-feedback></modal-feedback>
    <modal-feedback-full></modal-feedback-full>
    <modal-add-address></modal-add-address>
    <modal-cancel-order></modal-cancel-order>
@endsection
