@extends('layouts.layouts')
@section('title')
    Вакансии
@endsection
@section('head-js')
    <script defer src="{{ asset('js/vacancies.js') }}"></script>
@endsection
@section('head-css')
    <link href="{{ asset('css/vacancies.css') }}" rel="stylesheet">
@endsection
@section('style-body')
    class="body-min"
@endsection
@section('svg-icons')
    <svg-icons></svg-icons>
@endsection
@section('aside')
    <aside-main></aside-main>
@endsection
@section('header')
    <header-main></header-main>
@endsection
@section('content')
    <page-vacancies></page-vacancies>
@endsection
@section('footer')
    <footer-main></footer-main>
@endsection
@section('template')
    <modal-vacancy></modal-vacancy>
@endsection
